source $HOME/.config/nvim/vim-plug/plugins.vim
source $HOME/.config/nvim/settings/general.vim
source $HOME/.config/nvim/keys/mappings.vim
source $HOME/.config/nvim/keys/lsp-config.vim
source $HOME/.config/nvim/themes/theme.vim
source $HOME/.config/nvim/plugins/lightline.vim
source $HOME/.config/nvim/plugins/vim-sneak.vim
source $HOME/.config/nvim/plugins/quickscope.vim
source $HOME/.config/nvim/plugins/completion-nvim.vim
luafile $HOME/.config/nvim/plugins/lsp.lua
