return {
	"WhoIsSethDaniel/mason-tool-installer.nvim",
	enabled = false,
	opts = {
		ensure_installed = {
			-- "typescript-language-server",
			-- "js-debug-adapter",
			-- "biome",
			-- "css-lsp",
			-- "html-lsp",
			-- "lua-language-server",
			-- "luacheck",
			-- "stylua",
			-- "gopls",
			-- "gofumpt",
			-- "goimports",
			-- "golines",
			-- "golangci-lint",
			-- "delve",
			-- "pyright",
			-- "ruff",
			-- "clangd",
			-- "codelldb",
			-- "rust-analyzer",
			-- "solargraph",
			-- "zls",
		},
	},
	config = true,
}
