return {
	"WhoIsSethDaniel/mason-tool-installer.nvim",
	opts = {
		ensure_installed = {
			"typescript-language-server",
			"deno",
			"js-debug-adapter",
			"eslint_d",
			"prettierd",
			"css-lsp",
			"html-lsp",
			"pyright",
			"ruff",
			"debugpy",
			"lua-language-server",
			"luacheck",
			"stylua",
			"gopls",
			"gofumpt",
			"goimports",
			"golines",
			"golangci-lint",
			"delve",
			"clangd",
			"codelldb",
			"solargraph",
			"omnisharp",
			"rust-analyzer",
			"zls",
			-- "mypy",
			-- "flake8",
			-- "black",
			-- "isort",
		},
	},
	config = true,
}
