return {
	"WhoIsSethDaniel/mason-tool-installer.nvim",
	opts = {
		ensure_installed = {
			"typescript-language-server",
			"deno",
			"js-debug-adapter",
			"css-lsp",
			"html-lsp",
			"lua-language-server",
			"luacheck",
			"stylua",
			"gopls",
			"gofumpt",
			"goimports",
			"golines",
			"golangci-lint",
			"delve",
			"clangd",
			"codelldb",
			"rust-analyzer",
			"solargraph",
			"omnisharp",
			"zls",
		},
	},
	config = true,
}
